name = "external_pink_boa-32b7"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "external_pink_boa-32b7_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "external_pink_boa-32b7.wasm"
command = "npm run build:release"
